// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace OpenInWindowsTerminal
{
    internal sealed partial class Vsix
    {
        public const string Id = "A143B55E-D472-46E4-86F3-78BECD8F2584";
        public const string Name = "Open in Windows Terminal";
        public const string Description = @"Adds a menu command that lets you open any solution, project, folder and file in Windows Terminal.";
        public const string Language = "en-US";
        public const string Version = "1.3";
        public const string Author = "Josh Di-Duca";
        public const string Tags = "WindowsTerminal, terminal, open in, open with";
    }
}
