// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace OpenInWindowsTerminal
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidPackageString = "84C6ADE0-2DA3-4306-A182-01490F011492";
        public static Guid guidPackage = new Guid(guidPackageString);

        public const string guidOpenInWindowsTerminalCmdSetString = "0232B9F6-1DE1-40D2-831B-D52ABA00ED41";
        public static Guid guidOpenInWindowsTerminalCmdSet = new Guid(guidOpenInWindowsTerminalCmdSetString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int OpenInWindowsTerminal = 0x0200;
    }
}